-- Additive POS/inventory hardening. Existing stock, sales, and historical records are preserved.
ALTER TABLE `StockMovement` MODIFY `type` ENUM('OPENING_STOCK','ONLINE_RESERVATION','ONLINE_SALE','OFFLINE_SALE','RESERVATION_RELEASE','ORDER_CANCELLED','DELIVERY_FAILED','RETURN_RECEIVED','DAMAGED','EXPIRED','CORRECTION','SALE','RETURN','MANUAL_ADJUSTMENT','RESTOCK','CANCELLED_ORDER','PURCHASE','REFUND','PAYMENT_FAILURE','TRANSFER','AUDIT','STOCK_INWARD','LOST','STOLEN','TRANSFER_IN','TRANSFER_OUT','AUDIT_CORRECTION') NOT NULL;

ALTER TABLE `Inventory`
  ADD COLUMN `expired` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `safetyStock` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `reorderLevel` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `incoming` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `outgoing` INTEGER NOT NULL DEFAULT 0;

ALTER TABLE `OfflineSale`
  ADD COLUMN `idempotencyKey` VARCHAR(191) NULL,
  ADD COLUMN `customerReference` VARCHAR(191) NULL,
  ADD COLUMN `paymentMethod` VARCHAR(191) NOT NULL DEFAULT 'CASH',
  ADD COLUMN `cashReceived` DECIMAL(10, 2) NULL,
  ADD COLUMN `changeDue` DECIMAL(10, 2) NULL;

CREATE UNIQUE INDEX `OfflineSale_idempotencyKey_key` ON `OfflineSale`(`idempotencyKey`);
CREATE INDEX `OfflineSale_paymentMethod_idx` ON `OfflineSale`(`paymentMethod`);
